development:
    DATABASE_PASSWORD: 'password'
test:
    DATABASE_PASSWORD: 'password'
production:
    DATABASE_PASSWORD: 'password'
PUBLISHABLE_KEY: 'pk_test_fuVgqaEYDyxcMHpSwkZJo4fK'
SECRET_KEY: 'sk_test_ATn6Cl5eVxgcwgMPgq5519YR'